---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "apiservice-config"
  labels:
    app.kubernetes.io/name: "aspire-app"
    app.kubernetes.io/component: "apiservice"
    app.kubernetes.io/instance: "{{.Release.Name}}"
data:
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "{{ .Values.config.apiservice.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "{{ .Values.config.apiservice.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.apiservice.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.apiservice.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.config.apiservice.HTTP_PORTS }}"
  AUDIT_LOG_HOST: "{{ .Values.config.apiservice.AUDIT_LOG_HOST }}"
  AUDIT_LOG_PORT: "{{ .Values.config.apiservice.AUDIT_LOG_PORT }}"
  AUDIT_LOG_USERNAME: "{{ .Values.config.apiservice.AUDIT_LOG_USERNAME }}"
  AUDIT_LOG_JDBCCONNECTIONSTRING: "{{ .Values.config.apiservice.AUDIT_LOG_JDBCCONNECTIONSTRING }}"
  AUDIT_LOG_DATABASENAME: "{{ .Values.config.apiservice.AUDIT_LOG_DATABASENAME }}"
  ConnectionStrings__kafka: "{{ .Values.config.apiservice.ConnectionStrings__kafka }}"
  KAFKA_HOST: "{{ .Values.config.apiservice.KAFKA_HOST }}"
  KAFKA_PORT: "{{ .Values.config.apiservice.KAFKA_PORT }}"
  GATEWAY_HTTP: "{{ .Values.config.apiservice.GATEWAY_HTTP }}"
  services__gateway__http__0: "{{ .Values.config.apiservice.services__gateway__http__0 }}"
