---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "apiservice-secrets"
  labels:
    app.kubernetes.io/name: "aspire-app"
    app.kubernetes.io/component: "apiservice"
    app.kubernetes.io/instance: "{{.Release.Name}}"
stringData:
  ConnectionStrings__audit-log: "Host=postgres-service;Port=5432;Username={{ .Values.config.apiservice.postgres_user }};Password={{ .Values.secrets.apiservice.postgres_password }};Database=audit-log"
  AUDIT_LOG_PASSWORD: "{{ .Values.secrets.apiservice.postgres_password }}"
  AUDIT_LOG_URI: "postgresql://{{ .Values.config.apiservice.postgres_user }}:{{ .Values.secrets.apiservice.postgres_password }}@postgres-service:5432/audit-log"
type: "Opaque"
