---
apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  name: "kafka-statefulset"
  labels:
    app.kubernetes.io/name: "aspire-app"
    app.kubernetes.io/component: "kafka"
    app.kubernetes.io/instance: "{{.Release.Name}}"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "aspire-app"
        app.kubernetes.io/component: "kafka"
        app.kubernetes.io/instance: "{{.Release.Name}}"
    spec:
      containers:
        - image: "docker.io/confluentinc/confluent-local:8.1.0"
          name: "kafka"
          envFrom:
            - configMapRef:
                name: "kafka-config"
          ports:
            - name: "tcp"
              protocol: "TCP"
              containerPort: 9092
            - name: "internal"
              protocol: "TCP"
              containerPort: 9093
          imagePullPolicy: "IfNotPresent"
  selector:
    matchLabels:
      app.kubernetes.io/name: "aspire-app"
      app.kubernetes.io/component: "kafka"
      app.kubernetes.io/instance: "{{.Release.Name}}"
  replicas: 1
  persistentVolumeClaimRetentionPolicy: {}
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 0
    type: "RollingUpdate"
